Repository jsk-ros-pkg/jsk_3rdparty, pull requests merged in 2020-07, with the labels that each got.

#205 [gdrive_ros] Fix gdrive_ros to catch error properly
  gdrive_ros/node_scripts/gdrive_server_node.py
Labels: bug

#144 add more arg options for julius.launch
  julius_ros/launch/julius.launch
Labels: NeedReview

#203 fix typo in julius_client.py
  julius_ros/scripts/julius_client.py
  ros_speech_recognition/scripts/speech_recognition_node.py
Labels: MergeOK

#208 [dialogflow_task_executive] accepct full name of app name for dialogflow action
  dialogflow_task_executive/README.md
  dialogflow_task_executive/node_scripts/task_executive.py
Labels: enhancement
