Repository jsk-ros-pkg/jsk_3rdparty, pull requests merged in 2021-12, with the labels that each got.

#307 Support dialogflow hotword yaml
  dialogflow_task_executive/config/dialogflow_hotword.yaml
  dialogflow_task_executive/launch/dialogflow_task_executive.launch
  dialogflow_task_executive/node_scripts/dialogflow_client.py
Labels: MergeOK

#303 [ros_speech_recognition] add SpeechRecognitionCandidatesToString node
  ros_speech_recognition/CMakeLists.txt
  ros_speech_recognition/launch/speech_recognition.launch
  ros_speech_recognition/scripts/speech_recognition_candidates_to_string.py
  ros_speech_recognition/test/sample_ros_speech_recognition.test
Labels: enhancement, MergeOK

#301 [ros_speech_recognition] add auto_start in speech_recognition_node.py
  ros_speech_recognition/scripts/speech_recognition_node.py
Labels: enhancement, MergeOK

#294 add install section to switchbot_ros/CMakeLists.txt
  switchbot_ros/CMakeLists.txt
Labels: MergeOK

#318 [dialogflow_task_executive] Fix merging #317
  dialogflow_task_executive/node_scripts/dialogflow_client.py
Labels: bug

#319 [dialogflow_task_executive] load dialogflow project_id from credentials
  dialogflow_task_executive/node_scripts/dialogflow_client.py
Labels: enhancement
