Repository jsk-ros-pkg/jsk_3rdparty, pull requests merged in 2021-05, with the labels that each got.

#244 fix load_parameters: unable to set parameters
  ros_speech_recognition/launch/speech_recognition.launch
  ros_speech_recognition/scripts/speech_recognition_node.py
  ros_speech_recognition/src/ros_speech_recognition/recognize_google_cloud.py
Labels: MergeOK

#233 [gdrive_ros] update doc links
  gdrive_ros/README.md
Labels: MergeOK, bug

#238 [jsk_3rdparty] fix typo of dirname
  jsk_3rdparty/CHANGELOG.rst
  jsk_3rdparty/CMakeLists.txt
  jsk_3rdparty/package.xml
Labels: MergeOK

#240 [gdrive_ros] catch ServerNotFoundError in gdrive_server_node.py
  gdrive_ros/node_scripts/gdrive_server_node.py
Labels: MergeOK

#241 Reduce respeaker_node cpu usage
  respeaker_ros/launch/sample_respeaker.launch
  respeaker_ros/scripts/respeaker_node.py
Labels: MergeOK

#227 add "sound_play_topic" argument
  3rdparty/aques_talk/launch/aques_talk.launch
Labels: MergeOK

#221 [dialogflow_task_executive] Change mux namespace for speech_to_text
  dialogflow_task_executive/launch/dialogflow_task_executive.launch
Labels: MergeOK, hacktoberfest-accepted

#235 [rostwitter] add tweet_image_server.py
  rostwitter/CMakeLists.txt
  rostwitter/action/Tweet.action
  rostwitter/package.xml
  rostwitter/python/rostwitter/__init__.py
  rostwitter/python/rostwitter/twitter.py
  rostwitter/python/rostwitter/util.py
  rostwitter/resource/camera.wav
  rostwitter/scripts/tweet.py
  rostwitter/scripts/tweet_image_server.py
  rostwitter/setup.py
Labels: enhancement
