Repository jsk-ros-pkg/jsk_3rdparty, pull requests merged in 2022-12, with the labels that each got.

#413 [ros_speech_recognition] add self cancellation for speech recogntion
  ros_speech_recognition/README.md
  ros_speech_recognition/launch/speech_recognition.launch
  ros_speech_recognition/scripts/speech_recognition_node.py
Labels: bug

#411 [ros_speech_recogniton, respeaker_ros] add confidence field
  respeaker_ros/scripts/speech_to_text.py
  ros_speech_recognition/scripts/speech_recognition_node.py
Labels: bug, MergeOK

#408 [dialogflow_task_executive] check if ROS_PYTHON_VERSION is set to support indigo in dialogflow_client
  dialogflow_task_executive/node_scripts/dialogflow_client.py
Labels: bug, MergeOK

#385 [respeaker_ros] Stop timer on shutdown
  respeaker_ros/scripts/respeaker_node.py
Labels: MergeOK
