Repository jsk-ros-pkg/jsk_3rdparty, pull requests merged in 2023-01, with the labels that each got.

#403 [google_chat_ros] save google chat image in /chat_notification with timestamp
  google_chat_ros/scripts/google_chat_ros_node.py
Labels: MergeOK

#370 rostwitter : install resource directory
  rostwitter/CMakeLists.txt
Labels: MergeOK

#412 [ros_ speech_recognition] update default arg for speech_recognition.launch
  ros_speech_recognition/README.md
  ros_speech_recognition/launch/speech_recognition.launch
  ros_speech_recognition/scripts/speech_recognition_node.py
  ros_speech_recognition/test/sample_ros_speech_recognition.test
Labels: enhancement, question, MergeOK

#389 add zdepth and zdepth_image_transport package
  3rdparty/zdepth/CMakeLists.txt
  3rdparty/zdepth/fix_cmakelists.patch
  3rdparty/zdepth/package.xml
  jsk_3rdparty/package.xml
  zdepth_image_transport/CMakeLists.txt
  zdepth_image_transport/include/zdepth_image_transport/zdepth_publisher.h
  zdepth_image_transport/include/zdepth_image_transport/zdepth_subscriber.h
  zdepth_image_transport/msg/ZDepthImage.msg
  zdepth_image_transport/package.xml
  zdepth_image_transport/src/manifest.cpp
  zdepth_image_transport/src/test/zdepth_test.cpp
  zdepth_image_transport/src/zdepth_publisher.cpp
  zdepth_image_transport/src/zdepth_subscriber.cpp
  zdepth_image_transport/zdepth_plugins.xml
Labels: enhancement, MergeOK, PleaseFixCI

#406 Add nfc_ros
  jsk_3rdparty/package.xml
  nfc_ros/CMakeLists.txt
  nfc_ros/README.md
  nfc_ros/launch/demo.launch
  nfc_ros/msg/NDEFRecord.msg
  nfc_ros/msg/Tag.msg
  nfc_ros/node_scripts/nfc_ros_node.py
  nfc_ros/package.xml
  nfc_ros/python/nfc_ros/__init__.py
  nfc_ros/python/nfc_ros/nfc_interface.py
  nfc_ros/python/nfc_ros/nfc_ros_node.py
  nfc_ros/requirements.txt
  nfc_ros/setup.py
Labels: MergeOK
