Repository jsk-ros-pkg/jsk_3rdparty, pull requests merged in 2023-02, with the labels that each got.

#429 [gdrive_ros] fix sys.version error
  gdrive_ros/node_scripts/gdrive_server_node.py
Labels: bug, MergeOK

#428 [respeaker_ros] add FileNotFoundError in respeaker for python3
  respeaker_ros/scripts/respeaker_node.py
Labels: bug, MergeOK

#427 [zdepth, zdepth_image_transport] fix zdepth package version to 2.1.24
  3rdparty/zdepth/package.xml
  zdepth_image_transport/package.xml
Labels: bug, MergeOK

#426 [jsk_3rdparty] fix typo in package.xml
  jsk_3rdparty/package.xml
Labels: bug, MergeOK

#414 [ros_speech_recognition] add parrotry.launch
  ros_speech_recognition/README.md
  ros_speech_recognition/launch/parrotry.launch
  ros_speech_recognition/scripts/parrot_node.py
Labels: enhancement, MergeOK

#430 [zdepth_image_transport] add readme for zdepth_image_transport
  zdepth_image_transport/README.md
Labels: enhancement, document

#387 [aques_talk] build as x86 when dpkg cpu check fails
  3rdparty/aques_talk/CMakeLists.txt
  3rdparty/aques_talk/test/test_aques_talk.py
  3rdparty/aques_talk/test/test_aques_talk.test
  3rdparty/aques_talk/text2wave
Labels: bug

#419 [CI] build catkin_virtualenv packages in indigo.
  .github/workflows/config.yml
  .travis.rosinstall.indigo
  dialogflow_task_executive/CMakeLists.txt
Labels: bug

#379 [influxdb_store] add stop_all_services.bash
  influxdb_store/scripts/stop_all_services.bash
Labels: enhancement

#398 [tweet_image_server] control volume by dynamic_reconfigure
  rostwitter/CMakeLists.txt
  rostwitter/cfg/TweetImageServer.cfg
  rostwitter/package.xml
  rostwitter/scripts/tweet_image_server.py
Labels: MergeOK

#434 [ros_speech_recognition] Set confidence when using Google
  ros_speech_recognition/scripts/speech_recognition_node.py
Labels: ros_speech_recognition
